/// Port of: template/pipeline/ir/src/ops/create.ts (2095 LoC)
/// DOD + Arena Memory
const std = @import("std");

pub const LocalRef = struct {};
pub const ElementOrContainerOpBase = struct {};
pub const ElementOpBase = struct {};
pub const ElementStartOp = struct {};
pub const ForeignComponentOp = struct {};
pub const ContentOp = struct {};
pub const ElementOp = struct {};
pub const TemplateOp = struct {};
pub const ConditionalCreateOp = struct {};
pub const ConditionalBranchCreateOp = struct {};
pub const RepeaterCreateOp = struct {};
pub const RepeaterVarNames = struct {};
pub const ElementEndOp = struct {};
pub const ContainerStartOp = struct {};
pub const ContainerOp = struct {};
pub const ContainerEndOp = struct {};
pub const DisableBindingsOp = struct {};
pub const EnableBindingsOp = struct {};
pub const TextOp = struct {};
pub const AnimationStringOp = struct {};
pub const AnimationOp = struct {};
pub const ListenerOp = struct {};
pub const AnimationListenerOp = struct {};
pub const TwoWayListenerOp = struct {};
pub const PipeOp = struct {};
pub const NamespaceOp = struct {};
pub const ProjectionDefOp = struct {};
pub const EnableIncrementalHydrationRuntimeOp = struct {};
pub const ProjectionOp = struct {};
pub const ExtractedAttributeOp = struct {};
pub const DeferOp = struct {};
pub const DeferOnOp = struct {};
pub const DeclareLetOp = struct {};
pub const I18nParamValue = struct {};
pub const I18nMessageOp = struct {};
pub const I18nOpBase = struct {};
pub const I18nOp = struct {};
pub const I18nStartOp = struct {};
pub const I18nEndOp = struct {};
pub const IcuStartOp = struct {};
pub const IcuEndOp = struct {};
pub const IcuPlaceholderOp = struct {};
pub const I18nContextOp = struct {};
pub const I18nAttributesOp = struct {};
pub const ElementSourceLocation = struct {};
pub const SourceLocationOp = struct {};
pub const ControlCreateOp = struct {};
pub fn isElementOrContainerOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createElementStartOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createForeignComponentOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createContentOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createTemplateOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createConditionalCreateOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createConditionalBranchCreateOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createRepeaterCreateOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createElementEndOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createDisableBindingsOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createEnableBindingsOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createTextOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createAnimationStringOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createAnimationOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createListenerOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createAnimationListenerOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createTwoWayListenerOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createPipeOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createNamespaceOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createProjectionDefOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createEnableIncrementalHydrationRuntimeOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createProjectionOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createExtractedAttributeOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createDeferOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createDeferOnOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createDeclareLetOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createI18nMessageOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createI18nStartOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createI18nEndOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createIcuStartOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createIcuEndOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createIcuPlaceholderOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createI18nContextOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createI18nAttributesOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createSourceLocationOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub fn createControlCreateOp(allocator: std.mem.Allocator) void { _ = allocator; }
pub const CreateOp = anytype;
pub const ElementOrContainerOps = anytype;
pub const DeferTrigger = anytype;
pub const ConstIndex = anytype;

test "module loads" { std.testing.expect(true); }