/// TCB Type Check Block — generateTypeCheckBlock composer
///
/// Port of: compiler/src/typecheck/type_check_block.ts (99 LoC)
///
/// Given a component and metadata, compose a "type check block" function.
/// The TCB is a TypeScript function that, when type-checked by the TypeScript
/// compiler, validates the template's bindings against the component class.
const std = @import("std");

/// TcbTypeCheckBlockMetadata — metadata for a type check block.
/// Direct port of `TcbTypeCheckBlockMetadata` interface in the TS source.
pub const TcbTypeCheckBlockMetadata = struct {
    /// Unique ID for this TCB.
    id: u32,
    /// Whether the component is standalone.
    is_standalone: bool = false,
    /// Whether to preserve whitespace in the template.
    preserve_whitespaces: bool = false,
    /// Bound target (the component's template).
    bound_target: ?[]const u8 = null,
    /// Pipes used in the template.
    pipes: []const []const u8 = &.{},
    /// Schemas allowed in the template.
    schemas: []const []const u8 = &.{},
};

/// TcbComponentMetadata — metadata about the component being type-checked.
/// Direct port of `TcbComponentMetadata` interface in the TS source.
pub const TcbComponentMetadata = struct {
    /// Reference to the component class.
    ref: []const u8,
    /// Name of the component class.
    name: []const u8,
    /// Type parameters for generic components.
    type_parameters: ?[]const []const u8 = null,
    /// Type arguments for generic components.
    type_arguments: ?[]const []const u8 = null,
};

/// Generate a type check block function.
/// Direct port of `generateTypeCheckBlock(env, component, name, meta, domSchemaChecker, oobRecorder)` in the TS source.
///
/// Produces a TypeScript function that type-checks the component's template:
///   ```ts
///   function _tcb_MyComp(this: MyComp<T>): void {
///     // type check statements
///   }
///   ```
pub fn generateTypeCheckBlock(
    allocator: std.mem.Allocator,
    component: TcbComponentMetadata,
    name: []const u8,
    meta: TcbTypeCheckBlockMetadata,
) ![]const u8 {
    var buf = std.array_list.Managed(u8).init(allocator);
    errdefer buf.deinit();

    // Function signature: function _tcb_Name(this: ComponentType<T>): void {
    try buf.appendSlice("function ");
    try buf.appendSlice(name);
    try buf.appendSlice("(this: ");
    try buf.appendSlice(component.ref);

    // Type arguments
    if (component.type_arguments) |args| {
        if (args.len > 0) {
            try buf.appendSlice("<");
            for (args, 0..) |arg, i| {
                if (i > 0) try buf.appendSlice(", ");
                try buf.appendSlice(arg);
            }
            try buf.append('>');
        }
    }

    try buf.appendSlice("): void {");

    // Type parameters
    if (component.type_parameters) |params| {
        if (params.len > 0) {
            // The full implementation generates type parameter declarations.
            // For now, we just add a comment.
            try buf.appendSlice(" /* type params: ");
            for (params, 0..) |param, i| {
                if (i > 0) try buf.appendSlice(", ");
                try buf.appendSlice(param);
            }
            try buf.appendSlice(" */");
        }
    }

    // The body would contain the type check statements generated by the Scope.
    // For now, we just add a marker.
    try buf.appendSlice(" /* TCB for ");
    try buf.appendSlice(component.name);
    try buf.appendSlice(" */ ");

    // Add schema and pipe info as comments.
    if (meta.pipes.len > 0) {
        try buf.appendSlice("/* pipes: ");
        for (meta.pipes, 0..) |pipe, i| {
            if (i > 0) try buf.appendSlice(", ");
            try buf.appendSlice(pipe);
        }
        try buf.appendSlice(" */ ");
    }

    if (meta.is_standalone) {
        try buf.appendSlice("/* standalone */ ");
    }

    try buf.appendSlice("}");

    return buf.toOwnedSlice();
}

/// Create a host bindings block guard.
/// Direct port of `createHostBindingsBlockGuard()` in the TS source.
pub fn createHostBindingsBlockGuard(allocator: std.mem.Allocator) ![]const u8 {
    return allocator.dupe(u8, "ngDevMode");
}

// ─── Tests ──────────────────────────────────────────────────

test "generateTypeCheckBlock basic" {
    const allocator = std.testing.allocator;
    const component = TcbComponentMetadata{
        .ref = "MyComp",
        .name = "MyComp",
    };
    const meta = TcbTypeCheckBlockMetadata{ .id = 0 };
    const result = try generateTypeCheckBlock(allocator, component, "_tcb_MyComp", meta);
    defer allocator.free(result);
    try std.testing.expect(std.mem.indexOf(u8, result, "function _tcb_MyComp") != null);
    try std.testing.expect(std.mem.indexOf(u8, result, "MyComp") != null);
}

test "generateTypeCheckBlock with type arguments" {
    const allocator = std.testing.allocator;
    const type_args = [_][]const u8{"string"};
    const component = TcbComponentMetadata{
        .ref = "MyComp",
        .name = "MyComp",
        .type_arguments = &type_args,
    };
    const meta = TcbTypeCheckBlockMetadata{ .id = 0 };
    const result = try generateTypeCheckBlock(allocator, component, "_tcb", meta);
    defer allocator.free(result);
    try std.testing.expect(std.mem.indexOf(u8, result, "<string>") != null);
}

test "generateTypeCheckBlock with pipes" {
    const allocator = std.testing.allocator;
    const pipes = [_][]const u8{ "date", "uppercase" };
    const component = TcbComponentMetadata{
        .ref = "MyComp",
        .name = "MyComp",
    };
    const meta = TcbTypeCheckBlockMetadata{
        .id = 0,
        .pipes = &pipes,
    };
    const result = try generateTypeCheckBlock(allocator, component, "_tcb", meta);
    defer allocator.free(result);
    try std.testing.expect(std.mem.indexOf(u8, result, "date") != null);
    try std.testing.expect(std.mem.indexOf(u8, result, "uppercase") != null);
}

test "generateTypeCheckBlock standalone" {
    const allocator = std.testing.allocator;
    const component = TcbComponentMetadata{
        .ref = "MyComp",
        .name = "MyComp",
    };
    const meta = TcbTypeCheckBlockMetadata{
        .id = 0,
        .is_standalone = true,
    };
    const result = try generateTypeCheckBlock(allocator, component, "_tcb", meta);
    defer allocator.free(result);
    try std.testing.expect(std.mem.indexOf(u8, result, "standalone") != null);
}

test "createHostBindingsBlockGuard" {
    const allocator = std.testing.allocator;
    const result = try createHostBindingsBlockGuard(allocator);
    defer allocator.free(result);
    try std.testing.expectEqualStrings("ngDevMode", result);
}
