name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0 # Update this version if you are using a newer version of Zig

      - name: Check Formatting
        run: zig fmt --check .

      - name: Run Tests
        run: zig build test
